
export const platformFees: Record<string, { name: string; amount: number; currency: string }> = {
  "IN": { "name": "India", "amount": 10, "currency": "INR" },
  "US": { "name": "United States", "amount": 1, "currency": "USD" },
  "GB": { "name": "United Kingdom", "amount": 1, "currency": "GBP" },
  "CA": { "name": "Canada", "amount": 1, "currency": "CAD" },
  "AU": { "name": "Australia", "amount": 1, "currency": "AUD" },
  "NZ": { "name": "New Zealand", "amount": 1, "currency": "NZD" },
  "RU": { "name": "Russia", "amount": 10, "currency": "RUB" },
  "BR": { "name": "Brazil", "amount": 1, "currency": "BRL" },
  "ZA": { "name": "South Africa", "amount": 10, "currency": "ZAR" },
  "AE": { "name": "United Arab Emirates", "amount": 10, "currency": "AED" },
  "SA": { "name": "Saudi Arabia", "amount": 10, "currency": "SAR" },
  "QA": { "name": "Qatar", "amount": 10, "currency": "QAR" },
  "OM": { "name": "Oman", "amount": 10, "currency": "OMR" },
  "KW": { "name": "Kuwait", "amount": 10, "currency": "KWD" },
  "EG": { "name": "Egypt", "amount": 10, "currency": "EGP" },
  "DE": { "name": "Germany", "amount": 1, "currency": "EUR" },
  "FR": { "name": "France", "amount": 1, "currency": "EUR" },
  "IT": { "name": "Italy", "amount": 1, "currency": "EUR" },
  "ES": { "name": "Spain", "amount": 1, "currency": "EUR" },
  "NL": { "name": "Netherlands", "amount": 1, "currency": "EUR" },
  "BE": { "name": "Belgium", "amount": 1, "currency": "EUR" },
  "PT": { "name": "Portugal", "amount": 1, "currency": "EUR" },
  "FI": { "name": "Finland", "amount": 1, "currency": "EUR" },
  "IE": { "name": "Ireland", "amount": 1, "currency": "EUR" },
  "GR": { "name": "Greece", "amount": 1, "currency": "EUR" },
  "AT": { "name": "Austria", "amount": 1, "currency": "EUR" },
  "SE": { "name": "Sweden", "amount": 1, "currency": "SEK" },
  "NO": { "name": "Norway", "amount": 1, "currency": "NOK" },
  "DK": { "name": "Denmark", "amount": 1, "currency": "DKK" },
  "CH": { "name": "Switzerland", "amount": 1, "currency": "CHF" },
  "BD": { "name": "Bangladesh", "amount": 10, "currency": "BDT" },
  "PK": { "name": "Pakistan", "amount": 10, "currency": "PKR" },
  "LK": { "name": "Sri Lanka", "amount": 10, "currency": "LKR" },
  "NP": { "name": "Nepal", "amount": 10, "currency": "NPR" },
  "MM": { "name": "Myanmar", "amount": 10, "currency": "MMK" },
  "SG": { "name": "Singapore", "amount": 1, "currency": "SGD" },
  "MY": { "name": "Malaysia", "amount": 1, "currency": "MYR" },
  "TH": { "name": "Thailand", "amount": 10, "currency": "THB" },
  "ID": { "name": "Indonesia", "amount": 10, "currency": "IDR" },
  "VN": { "name": "Vietnam", "amount": 10, "currency": "VND" },
  "PH": { "name": "Philippines", "amount": 10, "currency": "PHP" },
  "KR": { "name": "South Korea", "amount": 1, "currency": "KRW" },
  "JP": { "name": "Japan", "amount": 1, "currency": "JPY" },
  "HK": { "name": "Hong Kong", "amount": 1, "currency": "HKD" },
  "CN": { "name": "China", "amount": 1, "currency": "CNY" },
  "NG": { "name": "Nigeria", "amount": 10, "currency": "NGN" },
  "KE": { "name": "Kenya", "amount": 10, "currency": "KES" },
  "DEFAULT": { "name": "Default", "amount": 10, "currency": "USD" }
};
